paths:
  uploads: ""

collections_config:
  pages:
    path: ""
    output: true
    url: "/[slug]/"
    icon: wysiwyg
    _enabled_editors:
      - visual
      - source

_editables:
  content:
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
  text:
    bold: true
    italic: true
    link: true
  block:
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
